In [1]:
import pandas as pd

In [2]:
entities = pd.read_csv('data_entities.csv', encoding = "ISO-8859-1", sep=',')
entities

,entity_id,name,latitude,longitude,entity_type,street,start_date,end_date
0,testsixsq,Rua dos Campeões Europeus,41.162590,-8.585198,TrafficFlowObserved,Rua dos Campeões Europeus,NaN,NaN
1,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,R. Fernandes Tomás - 24 de Agosto,41.148406,-8.599094,TrafficFlowObserved,Rua de Fernandes Tomás,NaN,NaN
2,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,R. Camões - N-S,41.154960,-8.610091,TrafficFlowObserved,Rua de Camões,NaN,NaN
3,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,Av. Boavista - Casa da Música - E-O,41.158701,-8.633546,TrafficFlowObserved,Avenida da Boavista,NaN,NaN
4,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,Via Panorâmica - Faixa BUS,41.151096,-8.633818,TrafficFlowObserved,Rua de Entre Campos,NaN,NaN
...,...,...,...,...,...,...,...,...
181,urn:ngsi-ld:WeatherObserved:porto:weather:comm...,Serralves,41.156350,-8.662500,WeatherObserved,NaN,NaN,NaN
182,urn:ngsi-ld:WeatherObserved:porto:weather:ubiw...,Bolhão,41.150123,-8.607110,WeatherObserved,NaN,NaN,NaN
183,urn:ngsi-ld:WeatherObserved:porto:weather:ubiw...,Aliados - S.Bento,41.146045,-8.611184,WeatherObserved,NaN,NaN,NaN
184,urn:ngsi-ld:WeatherObserved:porto:weather:ubiw...,Marquês,41.161009,-8.604408,WeatherObserved,NaN,NaN,NaN
185,urn:ngsi-ld:WeatherObserved:porto:weather:ubiw...,Bonfim,41.148427,-8.598081,WeatherObserved,NaN,NaN,NaN

In [7]:
entities.groupby(['latitude', 'longitude']).count().sort_values('name',ascending=False)

,,entity_id,name,entity_type,street,start_date,end_date
latitude,longitude,,,,,,
41.164327,-8.636619,6,6,6,6,0,0
41.162596,-8.590796,4,4,4,0,0,0
41.180222,-8.605194,4,4,4,0,0,0
41.171862,-8.613186,4,4,4,0,0,0
41.183769,-8.603107,3,3,3,0,0,0
...,...,...,...,...,...,...,...
41.149545,-8.604632,1,1,1,1,0,0
41.149770,-8.607373,1,1,1,1,0,0
41.150122,-8.611092,1,1,1,1,0,0
41.150143,-8.620987,1,1,1,1,0,0
41.153323,-8.613461,1,1,1,1,0,0

In [12]:
data_17 = pd.read_csv('traffic_flow_2017.csv', encoding = "ISO-8859-1", sep=',')
data_18 = pd.read_csv('traffic_flow_2018.csv', encoding = "ISO-8859-1", sep=',')
data_19 = pd.read_csv('traffic_flow_2019.csv', encoding = "ISO-8859-1", sep=',')
data_21 = pd.read_csv('traffic_flow_2021.csv', encoding = "ISO-8859-1", sep=',')

/home/primity/.miniconda3/envs/eruditio/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (4,6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [13]:
print(data_17.columns)
print(data_18.columns)
print(data_19.columns)
print(data_21.columns)

Index(['entity_id', 'entity_type', 'dateobservedfrom', 'dateobservedto',
       'dataprovider', 'intensity', 'source', 'laneid', 'lanedirection',
       'date_from', 'time_from', 'name'],
      dtype='object')
Index(['entity_id', 'entity_type', 'dateobservedfrom', 'dateobservedto',
       'dataprovider', 'intensity', 'source', 'laneid', 'lanedirection',
       'date_from', 'time_from', 'name'],
      dtype='object')
Index(['entity_id', 'entity_type', 'dateobservedfrom', 'dateobservedto',
       'dataprovider', 'intensity', 'source', 'laneid', 'lanedirection',
       'date_from', 'time_from', 'name'],
      dtype='object')
Index(['entity_id', 'entity_type', 'dateobservedfrom', 'dateobservedto',
       'dataprovider', 'intensity', 'source', 'laneid', 'lanedirection',
       'date_from', 'time_from', 'name'],
      dtype='object')

In [14]:
all_yrs = pd.concat([data_17, data_18, data_19, data_21,])

In [19]:
all_yrs.shape

(25084038, 12)

In [23]:
all_yrs.dataprovider.unique()

array([nan, 'https://www.schreder.com/fr-ch/aboutus/Volumlight'],
      dtype=object)

In [26]:
all_yrs.dtypes

entity_id            object
entity_type          object
dateobservedfrom     object
dateobservedto       object
dataprovider         object
intensity             int64
source               object
laneid                int64
lanedirection       float64
date_from            object
time_from            object
name                 object
dtype: object

In [32]:
#all_yrs.dateobservedfrom = pd.to_datetime(all_yrs['dateobservedfrom'].str.strip(), format='%Y-%m-%d %H:%M:%S')
all_yrs.dateobservedto = pd.to_datetime(all_yrs['dateobservedto'].str.strip(), format='%Y-%m-%d %H:%M:%S')

In [33]:
all_yrs ['diff'] = all_yrs.dateobservedto- all_yrs.dateobservedfrom

In [41]:
all_yrs

,entity_id,entity_type,dateobservedfrom,dateobservedto,dataprovider,intensity,source,laneid,lanedirection,date_from,time_from,name,diff
0,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 05:40:00,2017-12-25 05:45:00,NaN,4,NaN,1,NaN,2017-12-25,05:40:00.0000000,R. Heroísmo,0 days 00:05:00
1,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 06:05:00,2017-12-25 06:10:00,NaN,1,NaN,1,NaN,2017-12-25,06:05:00.0000000,R. Heroísmo,0 days 00:05:00
2,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 06:45:00,2017-12-25 06:50:00,NaN,4,NaN,1,NaN,2017-12-25,06:45:00.0000000,R. Heroísmo,0 days 00:05:00
3,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 10:20:00,2017-12-25 10:25:00,NaN,1,NaN,1,NaN,2017-12-25,10:20:00.0000000,R. Mártires da Liberdade,0 days 00:05:00
4,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 10:35:00,2017-12-25 10:40:00,NaN,3,NaN,1,NaN,2017-12-25,10:35:00.0000000,R. Mártires da Liberdade,0 days 00:05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1778486,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2021-03-19 10:15:00,2021-03-19 10:20:00,NaN,22,NaN,1,NaN,2021-03-19,10:15:00.0000000,Av. Rodrigues de Freitas,0 days 00:05:00
1778487,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2021-03-19 10:15:00,2021-03-19 10:20:00,NaN,69,NaN,1,NaN,2021-03-19,10:15:00.0000000,R. Fontainhas,0 days 00:05:00
1778488,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2021-03-19 10:10:00,2021-03-19 10:15:00,NaN,18,NaN,1,NaN,2021-03-19,10:10:00.0000000,Av. Fernão Magalhães N-S - Túnel,0 days 00:05:00
1778489,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2021-03-19 10:10:00,2021-03-19 10:15:00,NaN,19,NaN,1,NaN,2021-03-19,10:10:00.0000000,R. Antero Quental - Constituição - S-N,0 days 00:05:00
1778490,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2021-03-19 10:10:00,2021-03-19 10:15:00,NaN,11,NaN,1,NaN,2021-03-19,10:10:00.0000000,R. Antero Quental - Damião de Góis - S-N,0 days 00:05:00

In [29]:
all_yrs.head(10)

,entity_id,entity_type,dateobservedfrom,dateobservedto,dataprovider,intensity,source,laneid,lanedirection,date_from,time_from,name
0,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 05:40:00,2017-12-25 05:45:00,NaN,4,NaN,1,NaN,2017-12-25,05:40:00.0000000,R. Heroísmo
1,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 06:05:00,2017-12-25 06:10:00,NaN,1,NaN,1,NaN,2017-12-25,06:05:00.0000000,R. Heroísmo
2,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 06:45:00,2017-12-25 06:50:00,NaN,4,NaN,1,NaN,2017-12-25,06:45:00.0000000,R. Heroísmo
3,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 10:20:00,2017-12-25 10:25:00,NaN,1,NaN,1,NaN,2017-12-25,10:20:00.0000000,R. Mártires da Liberdade
4,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 10:35:00,2017-12-25 10:40:00,NaN,3,NaN,1,NaN,2017-12-25,10:35:00.0000000,R. Mártires da Liberdade
5,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 11:15:00,2017-12-25 11:20:00,NaN,6,NaN,1,NaN,2017-12-25,11:15:00.0000000,R. Mártires da Liberdade
6,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 11:55:00,2017-12-25 12:00:00,NaN,8,NaN,1,NaN,2017-12-25,11:55:00.0000000,R. Mártires da Liberdade
7,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 12:15:00,2017-12-25 12:20:00,NaN,16,NaN,1,NaN,2017-12-25,12:15:00.0000000,R. Mártires da Liberdade
8,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 04:00:00,2017-12-25 04:05:00,NaN,5,NaN,1,NaN,2017-12-25,04:00:00.0000000,R. Antero Quental - Constituição - N-S
9,urn:ngsi-ld:TrafficFlowObserved:porto:traffic:...,TrafficFlowObserved,2017-12-25 05:30:00,2017-12-25 05:35:00,NaN,1,NaN,1,NaN,2017-12-25,05:30:00.0000000,R. Antero Quental - Constituição - N-S

In [43]:
all_yrs.laneid.unique()

array([1, 4, 3, 2, 5, 6])