In [1]:
import pandas as pd

In [54]:
population_dataframe = pd.DataFrame(columns=pd.read_csv('lisboa.csv', encoding='Latin-1', sep=';').columns)
for region in ['centro', 'lisboa', 'norte', 'alentejo', 'algarve']:
    population_dataframe = population_dataframe.append(pd.read_csv(f'{region}.csv', encoding='Latin-1', sep=';'), ignore_index=True)
    
population_dataframe = population_dataframe[population_dataframe.nivel==6]
population_dataframe['Zona Geográfica'] = population_dataframe['Zona Geográfica'].str.lstrip()

In [62]:
population_dataframe.to_csv('parishes_population.csv', index=False)

In [63]:
population_dataframe

,ordem,nivel,cod_dim2,Zona Geográfica,População residente - Total,População residente - H,População residente - M,População presente - Total,População presente - H,População presente - M,Famílias - Clássicas,Famílias - Institucionais,Núcleos familiares,Alojamentos familiares - Total,Alojamentos familiares - Clássicos,Alojamentos familiares - Não clássicos,Alojamentos colectivos,Edifícios clássicos
3,96349000,6,10101,Agadão,373,173,200,368,169,199,146,0,123,207,207,0,0,204
4,96374000,6,10102,Aguada de Baixo,1373,643,730,1322,611,711,478,1,431,622,622,0,3,574
5,96430000,6,10103,Aguada de Cima,4013,1943,2070,3806,1820,1986,1455,1,1265,2018,2014,4,2,1653
6,96580000,6,10104,Águeda,11346,5393,5953,11106,5217,5889,4382,5,3566,5860,5855,5,12,3485
7,96888000,6,10105,Barrô,1836,873,963,1792,851,941,653,1,596,842,840,2,1,784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4355,276730000,6,81504,Sagres,1909,943,966,2162,1075,1087,787,1,568,1580,1577,3,25,1349
4356,276827000,6,81505,Vila do Bispo,918,455,463,942,469,473,393,0,279,693,690,3,7,604
4358,276920000,6,81601,Vila Nova de Cacela,3902,1877,2025,4327,2111,2216,1598,1,1257,5570,5569,1,9,3780
4359,277102000,6,81602,Vila Real de Santo António,11946,5687,6259,11519,5463,6056,4656,4,3641,8026,8013,13,14,2720
4360,277394000,6,81603,Monte Gordo,3308,1589,1719,4750,2303,2447,1199,0,1002,6029,6027,2,16,1649